In [6]:
import numpy as np

from sklearn.metrics import multilabel_confusion_matrix

y_true = np.array([[1, 0, 1],
                   [0, 1, 0],
                   [1, 0, 0]])

y_pred = np.array([[1, 0, 0],
                   [0, 1, 1],
                   [1, 1, 1]])

cm = multilabel_confusion_matrix(y_true, y_pred)

In [7]:
cm

array([[[1, 0],
        [0, 2]],

       [[1, 1],
        [0, 1]],

       [[0, 2],
        [1, 0]]])

In [12]:
cm[:, 1, 1]

array([2, 1, 0])

In [19]:
cm[:, :, 1], np.sum(cm[:, :, 1])

(array([[0, 2],
        [1, 1],
        [2, 0]]),
 6)

In [21]:
np.sum(cm[:, 1, 1]) / np.sum(cm[:, :, 1])

0.5

In [14]:
np.sum(cm[:, :, 1], axis=1)

array([2, 2, 2])

In [16]:
np.average(cm[:, 1, 1] / np.sum(cm[:, :, 1], axis=1))

0.5

In [27]:
np.sum(cm[:, 1, :], axis=1)

array([2, 1, 1])

In [30]:
np.array([1, 0, 0]).astype(bool).shape

(3,)